CREATE TABLE TimeSlots (
	Id			SMALLINT	IDENTITY(1,1)	NOT NULL,
	Text		VARCHAR(32)					NOT NULL,

	CONSTRAINT TimeSlots_PK PRIMARY KEY ( ID )
);

GO

ALTER TABLE Sessions ADD TimeSlotId SMALLINT NULL;

